name: BanGuiPlugin
main: fr.floukiller.banguiplugin.Main
version: 1.0.0
api-version: 1.20
author: Floukiller
description: Plugin de bannissement avec une interface graphique

commands:
  bangui:
    description: Ouvre l'interface graphique de bannissement
    usage: /<command> <pseudo>
    permission: banguiplugin.bangui
    aliases: [bg]
  mute:
    description: Mute un joueur
    usage: /<command> <pseudo> <durée> <raison>
    permission: banguiplugin.mute
  unmute:
    description: Unmute un joueur
    usage: /<command> <pseudo>
    permission: banguiplugin.unmute